# Generated by Django 4.0 on 2023-01-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KiaKiaApp', '0003_subscribemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribeMail',
        ),
    ]
